services:

  slides-react-academy:
    image: slides-react-academy:latest
    container_name: slides-react-academy
    restart: unless-stopped
    expose:
      - "80"
    labels:
      - traefik.enable=true
      # HTTPS router
      - traefik.http.routers.react-academy.rule=Host(`slides.reactacademy.live`)
      - traefik.http.routers.react-academy.entrypoints=websecure
      - traefik.http.routers.react-academy.tls.certresolver=letsencrypt
      - traefik.http.services.react-academy.loadbalancer.server.port=80   
    networks:
      - stack_backend


networks:
  stack_backend:
    external: true


